<a href="https://colab.research.google.com/github/ViratK18/Data-Science-January/blob/Data-Science/KNN_Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import seaborn as sn
import matplotlib.pyplot as plt

In [2]:
dif = pd.read_csv('https://raw.githubusercontent.com/insignificantGuy/Kaggle-Datasets/main/csgo_round_snapshots.csv')

In [4]:
dif.head()

,time_left,ct_score,t_score,map,bomb_planted,ct_health,t_health,ct_armor,t_armor,ct_money,...,t_grenade_flashbang,ct_grenade_smokegrenade,t_grenade_smokegrenade,ct_grenade_incendiarygrenade,t_grenade_incendiarygrenade,ct_grenade_molotovgrenade,t_grenade_molotovgrenade,ct_grenade_decoygrenade,t_grenade_decoygrenade,round_winner
0,175.00,0.0,0.0,de_dust2,False,500.0,500.0,0.0,0.0,4000.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,CT
1,156.03,0.0,0.0,de_dust2,False,500.0,500.0,400.0,300.0,600.0,...,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,CT
2,96.03,0.0,0.0,de_dust2,False,391.0,400.0,294.0,200.0,750.0,...,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,CT
3,76.03,0.0,0.0,de_dust2,False,391.0,400.0,294.0,200.0,750.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,CT
4,174.97,1.0,0.0,de_dust2,False,500.0,500.0,192.0,0.0,18350.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,CT

In [7]:
dif.dtypes

time_left                    float64
ct_score                     float64
t_score                      float64
map                           object
bomb_planted                    bool
                              ...
ct_grenade_molotovgrenade    float64
t_grenade_molotovgrenade     float64
ct_grenade_decoygrenade      float64
t_grenade_decoygrenade       float64
round_winner                  object
Length: 97, dtype: object

In [8]:
dif.describe()

,time_left,ct_score,t_score,ct_health,t_health,ct_armor,t_armor,ct_money,t_money,ct_helmets,...,ct_grenade_flashbang,t_grenade_flashbang,ct_grenade_smokegrenade,t_grenade_smokegrenade,ct_grenade_incendiarygrenade,t_grenade_incendiarygrenade,ct_grenade_molotovgrenade,t_grenade_molotovgrenade,ct_grenade_decoygrenade,t_grenade_decoygrenade
count,122410.000000,122410.000000,122410.000000,122410.000000,122410.000000,122410.000000,122410.000000,122410.000000,122410.000000,122410.000000,...,122410.000000,122410.000000,122410.000000,122410.000000,122410.000000,122410.000000,122410.000000,122410.000000,122410.000000,122410.000000
mean,97.886922,6.709239,6.780435,412.106568,402.714500,314.142121,298.444670,9789.023773,11241.036680,2.053901,...,1.853157,1.858100,1.540814,1.627146,1.001969,0.019819,0.048011,1.352095,0.027694,0.025750
std,54.465238,4.790362,4.823543,132.293290,139.919033,171.029736,174.576545,11215.042286,12162.806759,1.841470,...,1.772791,1.794473,1.737804,1.829147,1.458084,0.143933,0.227669,1.663246,0.169531,0.164162
min,0.010000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,54.920000,3.000000,3.000000,350.000000,322.000000,194.000000,174.000000,1300.000000,1550.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,94.910000,6.000000,6.000000,500.000000,500.000000,377.000000,334.000000,5500.000000,7150.000000,2.000000,...,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000
75%,166.917500,10.000000,10.000000,500.000000,500.000000,486.000000,468.000000,14600.000000,18000.000000,4.000000,...,3.000000,3.000000,3.000000,3.000000,2.000000,0.000000,0.000000,2.000000,0.000000,0.000000
max,175.000000,32.000000,33.000000,500.000000,600.000000,500.000000,500.000000,80000.000000,80000.000000,5.000000,...,7.000000,7.000000,6.000000,9.000000,5.000000,3.000000,3.000000,5.000000,3.000000,2.000000

In [9]:
dif.describe

<bound method NDFrame.describe of         time_left  ct_score  t_score       map  bomb_planted  ct_health  \
0          175.00       0.0      0.0  de_dust2         False      500.0
1          156.03       0.0      0.0  de_dust2         False      500.0
2           96.03       0.0      0.0  de_dust2         False      391.0
3           76.03       0.0      0.0  de_dust2         False      391.0
4          174.97       1.0      0.0  de_dust2         False      500.0
...           ...       ...      ...       ...           ...        ...
122405      15.41      11.0     14.0  de_train          True      200.0
122406     174.93      11.0     15.0  de_train         False      500.0
122407     114.93      11.0     15.0  de_train         False      500.0
122408      94.93      11.0     15.0  de_train         False      500.0
122409      74.93      11.0     15.0  de_train         False      375.0

        t_health  ct_armor  t_armor  ct_money  ...  t_grenade_flashbang  \
0          500.0       0.0      0.0    4000.0  ...                  0.0
1          500.0     400.0    300.0     600.0  ...                  0.0
2          400.0     294.0    200.0     750.0  ...                  0.0
3          400.0     294.0    200.0     750.0  ...                  0.0
4          500.0     192.0      0.0   18350.0  ...                  0.0
...          ...       ...      ...       ...  ...                  ...
122405     242.0     195.0    359.0     100.0  ...                  2.0
122406     500.0      95.0    175.0   11500.0  ...                  2.0
122407     500.0     495.0    475.0    1200.0  ...                  4.0
122408     500.0     495.0    475.0    1200.0  ...                  5.0
122409     479.0     395.0    466.0    1100.0  ...                  3.0

        ct_grenade_smokegrenade  t_grenade_smokegrenade  \
0                           0.0                     0.0
1                           0.0                     2.0
2                           0.0                     2.0
3                           0.0                     0.0
4                           0.0                     0.0
...                         ...                     ...
122405                      1.0                     1.0
122406                      1.0                     0.0
122407                      3.0                     5.0
122408                      0.0                     3.0
122409                      0.0                     2.0

        ct_grenade_incendiarygrenade  t_grenade_incendiarygrenade  \
0                                0.0                          0.0
1                                0.0                          0.0
2                                0.0                          0.0
3                                0.0                          0.0
4                                0.0                          0.0
...                              ...                          ...
122405                           0.0                          0.0
122406                           0.0                          0.0
122407                           1.0                          0.0
122408                           0.0                          0.0
122409                           0.0                          0.0

        ct_grenade_molotovgrenade  t_grenade_molotovgrenade  \
0                             0.0                       0.0
1                             0.0                       0.0
2                             0.0                       0.0
3                             0.0                       0.0
4                             0.0                       0.0
...                           ...                       ...
122405                        0.0                       0.0
122406                        0.0                       0.0
122407                        0.0                       5.0
122408                        0.0                       4.0
122409                        0.0                       3.0

        ct_grenade_decoygrenade  t_grenade_decoygrenade  round_winner
0                           0.0                     0.0            CT
1                           0.0                     0.0            CT
2                           0.0                     0.0            CT
3                           0.0                     0.0            CT
4                           0.0                     0.0            CT
...                         ...                     ...           ...
122405                      0.0                     0.0             T
122406                      0.0                     0.0             T
122407                      0.0                     0.0             T
122408                      0.0                     0.0             T
122409                      0.0                     0.0             T

[122410 rows x 97 columns]>

In [10]:
dif.isna().sum()

time_left                    0
ct_score                     0
t_score                      0
map                          0
bomb_planted                 0
                            ..
ct_grenade_molotovgrenade    0
t_grenade_molotovgrenade     0
ct_grenade_decoygrenade      0
t_grenade_decoygrenade       0
round_winner                 0
Length: 97, dtype: int64

In [11]:
dif.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 122410 entries, 0 to 122409
Data columns (total 97 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   time_left                     122410 non-null  float64
 1   ct_score                      122410 non-null  float64
 2   t_score                       122410 non-null  float64
 3   map                           122410 non-null  object
 4   bomb_planted                  122410 non-null  bool
 5   ct_health                     122410 non-null  float64
 6   t_health                      122410 non-null  float64
 7   ct_armor                      122410 non-null  float64
 8   t_armor                       122410 non-null  float64
 9   ct_money                      122410 non-null  float64
 10  t_money                       122410 non-null  float64
 11  ct_helmets                    122410 non-null  float64
 12  t_helmets                     122410 non-null  float64
 13  ct_defuse_kits                122410 non-null  float64
 14  ct_players_alive              122410 non-null  float64
 15  t_players_alive               122410 non-null  float64
 16  ct_weapon_ak47                122410 non-null  float64
 17  t_weapon_ak47                 122410 non-null  float64
 18  ct_weapon_aug                 122410 non-null  float64
 19  t_weapon_aug                  122410 non-null  float64
 20  ct_weapon_awp                 122410 non-null  float64
 21  t_weapon_awp                  122410 non-null  float64
 22  ct_weapon_bizon               122410 non-null  float64
 23  t_weapon_bizon                122410 non-null  float64
 24  ct_weapon_cz75auto            122410 non-null  float64
 25  t_weapon_cz75auto             122410 non-null  float64
 26  ct_weapon_elite               122410 non-null  float64
 27  t_weapon_elite                122410 non-null  float64
 28  ct_weapon_famas               122410 non-null  float64
 29  t_weapon_famas                122410 non-null  float64
 30  ct_weapon_g3sg1               122410 non-null  float64
 31  t_weapon_g3sg1                122410 non-null  float64
 32  ct_weapon_galilar             122410 non-null  float64
 33  t_weapon_galilar              122410 non-null  float64
 34  ct_weapon_glock               122410 non-null  float64
 35  t_weapon_glock                122410 non-null  float64
 36  ct_weapon_m249                122410 non-null  float64
 37  t_weapon_m249                 122410 non-null  float64
 38  ct_weapon_m4a1s               122410 non-null  float64
 39  t_weapon_m4a1s                122410 non-null  float64
 40  ct_weapon_m4a4                122410 non-null  float64
 41  t_weapon_m4a4                 122410 non-null  float64
 42  ct_weapon_mac10               122410 non-null  float64
 43  t_weapon_mac10                122410 non-null  float64
 44  ct_weapon_mag7                122410 non-null  float64
 45  t_weapon_mag7                 122410 non-null  float64
 46  ct_weapon_mp5sd               122410 non-null  float64
 47  t_weapon_mp5sd                122410 non-null  float64
 48  ct_weapon_mp7                 122410 non-null  float64
 49  t_weapon_mp7                  122410 non-null  float64
 50  ct_weapon_mp9                 122410 non-null  float64
 51  t_weapon_mp9                  122410 non-null  float64
 52  ct_weapon_negev               122410 non-null  float64
 53  t_weapon_negev                122410 non-null  float64
 54  ct_weapon_nova                122410 non-null  float64
 55  t_weapon_nova                 122410 non-null  float64
 56  ct_weapon_p90                 122410 non-null  float64
 57  t_weapon_p90                  122410 non-null  float64
 58  ct_weapon_r8revolver          122410 non-null  float64
 59  t_weapon_r8revolver           122410 non-null  float64
 60  ct_weapon_sawedoff            122410 non-null  float64
 61  t_weapon_sawedoff             122410 non-null  float64
 62  ct_weapon_scar20              122410 non-null  float64
 63  t_weapon_scar20               122410 non-null  float64
 64  ct_weapon_sg553               122410 non-null  float64
 65  t_weapon_sg553                122410 non-null  float64
 66  ct_weapon_ssg08               122410 non-null  float64
 67  t_weapon_ssg08                122410 non-null  float64
 68  ct_weapon_ump45               122410 non-null  float64
 69  t_weapon_ump45                122410 non-null  float64
 70  ct_weapon_xm1014              122410 non-null  float64
 71  t_weapon_xm1014               122410 non-null  float64
 72  ct_weapon_deagle              122410 non-null  float64
 73  t_weapon_deagle               122410 non-null  float64
 74  ct_weapon_fiveseven           122410 non-null  float64
 75  t_weapon_fiveseven            122410 non-null  float64
 76  ct_weapon_usps                122410 non-null  float64
 77  t_weapon_usps                 122410 non-null  float64
 78  ct_weapon_p250                122410 non-null  float64
 79  t_weapon_p250                 122410 non-null  float64
 80  ct_weapon_p2000               122410 non-null  float64
 81  t_weapon_p2000                122410 non-null  float64
 82  ct_weapon_tec9                122410 non-null  float64
 83  t_weapon_tec9                 122410 non-null  float64
 84  ct_grenade_hegrenade          122410 non-null  float64
 85  t_grenade_hegrenade           122410 non-null  float64
 86  ct_grenade_flashbang          122410 non-null  float64
 87  t_grenade_flashbang           122410 non-null  float64
 88  ct_grenade_smokegrenade       122410 non-null  float64
 89  t_grenade_smokegrenade        122410 non-null  float64
 90  ct_grenade_incendiarygrenade  122410 non-null  float64
 91  t_grenade_incendiarygrenade   122410 non-null  float64
 92  ct_grenade_molotovgrenade     122410 non-null  float64
 93  t_grenade_molotovgrenade      122410 non-null  float64
 94  ct_grenade_decoygrenade       122410 non-null  float64
 95  t_grenade_decoygrenade        122410 non-null  float64
 96  round_winner                  122410 non-null  object
dtypes: bool(1), float64(94), object(2)
memory usage: 89.8+ MB

In [14]:
# get_dummies() is used for data manipulation. It converts categorical data into dummy or indicator variables
# if drop_first is true it removes the first column which is created for the first unique value of a column.

df= pd.get_dummies(dif, drop_first=True)

In [15]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
arr = scaler.fit_transform(df.drop('round_winner_T',axis=1))
newDf = pd.DataFrame(arr,columns=df.columns[:-1])

In [17]:
newDf

,time_left,ct_score,t_score,bomb_planted,ct_health,t_health,ct_armor,t_armor,ct_money,t_money,...,t_grenade_molotovgrenade,ct_grenade_decoygrenade,t_grenade_decoygrenade,map_de_dust2,map_de_inferno,map_de_mirage,map_de_nuke,map_de_overpass,map_de_train,map_de_vertigo
0,1.415828,-1.400576,-1.405702,-0.354764,0.664386,0.695301,-1.836777,-1.709542,-0.516186,-0.595345,...,-0.812929,-0.163356,-0.156855,2.127888,-0.49142,-0.422967,-0.428977,-0.360532,-0.351941,-0.316366
1,1.067531,-1.400576,-1.405702,-0.354764,0.664386,0.695301,0.502008,0.008909,-0.819351,-0.870776,...,-0.812929,-0.163356,-0.156855,2.127888,-0.49142,-0.422967,-0.428977,-0.360532,-0.351941,-0.316366
2,-0.034094,-1.400576,-1.405702,-0.354764,-0.159544,-0.019401,-0.117770,-0.563908,-0.805977,-0.883109,...,-0.812929,-0.163356,-0.156855,2.127888,-0.49142,-0.422967,-0.428977,-0.360532,-0.351941,-0.316366
3,-0.401302,-1.400576,-1.405702,-0.354764,-0.159544,-0.019401,-0.117770,-0.563908,-0.805977,-0.883109,...,-0.812929,-0.163356,-0.156855,2.127888,-0.49142,-0.422967,-0.428977,-0.360532,-0.351941,-0.316366
4,1.415277,-1.191823,-1.405702,-0.354764,0.664386,0.695301,-0.714160,-1.709542,0.763351,-0.040372,...,-0.812929,-0.163356,-0.156855,2.127888,-0.49142,-0.422967,-0.428977,-0.360532,-0.351941,-0.316366
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
122405,-1.514310,0.895711,1.496741,2.818773,-1.603312,-1.148630,-0.696619,0.346871,-0.863935,-0.435020,...,-0.812929,-0.163356,-0.156855,-0.469949,-0.49142,-0.422967,-0.428977,-0.360532,2.841383,-0.316366
122406,1.414542,0.895711,1.704058,-0.354764,0.664386,0.695301,-1.281315,-0.707112,0.152561,1.040797,...,-0.812929,-0.163356,-0.156855,-0.469949,-0.49142,-0.422967,-0.428977,-0.360532,2.841383,-0.316366
122407,0.312918,0.895711,1.704058,-0.354764,0.664386,0.695301,1.057469,1.011339,-0.765852,-0.373356,...,2.193253,-0.163356,-0.156855,-0.469949,-0.49142,-0.422967,-0.428977,-0.360532,2.841383,-0.316366
122408,-0.054290,0.895711,1.704058,-0.354764,0.664386,0.695301,1.057469,1.011339,-0.765852,-0.373356,...,1.592017,-0.163356,-0.156855,-0.469949,-0.49142,-0.422967,-0.428977,-0.360532,2.841383,-0.316366
122409,-0.421498,0.895711,1.704058,-0.354764,-0.280488,0.545214,0.472773,0.959785,-0.774768,-0.348690,...,0.990780,-0.163356,-0.156855,-0.469949,-0.49142,-0.422967,-0.428977,-0.360532,2.841383,-0.316366

In [18]:
x_all = newDf
y_all = df['round_winner_T']

In [19]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x_all,y_all,test_size=0.17,random_state=42)

In [20]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=3)

In [21]:
predict = knn.predict(x_test)

In [22]:
knn.score(x_test,y_test)

0.8691975012013455

In [23]:
from sklearn.metrics import confusion_matrix, classification_report
matrix = confusion_matrix(y_test,predict)
matrix

array([[8793, 1370],
       [1352, 9295]])

In [24]:
print(classification_report(y_test,predict))

              precision    recall  f1-score   support

           0       0.87      0.87      0.87     10163
           1       0.87      0.87      0.87     10647

    accuracy                           0.87     20810
   macro avg       0.87      0.87      0.87     20810
weighted avg       0.87      0.87      0.87     20810